package com.tc.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tc.greendao.TraceEvidence;
import com.tc.greendao.User;
import com.tc.greendao.Criminal;

import com.tc.greendao.TraceEvidenceDao;
import com.tc.greendao.UserDao;
import com.tc.greendao.CriminalDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig traceEvidenceDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig criminalDaoConfig;

    private final TraceEvidenceDao traceEvidenceDao;
    private final UserDao userDao;
    private final CriminalDao criminalDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        traceEvidenceDaoConfig = daoConfigMap.get(TraceEvidenceDao.class).clone();
        traceEvidenceDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        criminalDaoConfig = daoConfigMap.get(CriminalDao.class).clone();
        criminalDaoConfig.initIdentityScope(type);

        traceEvidenceDao = new TraceEvidenceDao(traceEvidenceDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        criminalDao = new CriminalDao(criminalDaoConfig, this);

        registerDao(TraceEvidence.class, traceEvidenceDao);
        registerDao(User.class, userDao);
        registerDao(Criminal.class, criminalDao);
    }
    
    public void clear() {
        traceEvidenceDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        criminalDaoConfig.clearIdentityScope();
    }

    public TraceEvidenceDao getTraceEvidenceDao() {
        return traceEvidenceDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public CriminalDao getCriminalDao() {
        return criminalDao;
    }

}
